### ISSUE TITLE
API endpoint to print image

### ISSUE THREAD

**Issue by FriedrichFroebel** [FriedrichFroebel/brother_ql_web#14]
Add API endpoint to print an image directly.

**Comment by tobru** [comment]
That sounds interesting, do you have any plans to do that in the future?

**Comment by FriedrichFroebel** [comment]
I have no direct plans or schedule for this at the moment, but it shouldn't be too hard to implement as the printing backend is image-based anyway, thus the implementation is an easier variant of the text functionality. I might have a look at this in the near future.

**Comment by FriedrichFroebel** [comment]
A corresponding endpoint is now available, although not yet released and not available in the GUI. You can call it like this:

```python3
import requests


with open("image.png", mode="rb") as fd:
    image_data = fd.read()

response = requests.post(
    url="http://localhost:8013/api/print/image?label_size=62&orientation=standard"
    files={"image": image_data},
)
print(response)
```

**Comment by tobru** [comment]
Very cool, thanks a lot! I'll certainly can make use of that.

**Comment by FriedrichFroebel** [comment]
Version 0.3.0 including this change has just been deployed to PyPI.
