### ISSUE TITLE
Bootstraps javascript requires jquery

### ISSUE THREAD

**Issue by segadora** [FriedrichFroebel/brother_ql_web#25]
Hello

error in browser
```
bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6:37
(anonymous) @ bootstrap.min.js:6
```

**Comment by FriedrichFroebel** [comment]
Could you please provide some more details? I cannot reproduce this with the latest Firefox. The PyPI releases and this fork all use Bootstrap 5 which dropped the hard requirement on jQuery and I migrated everything to plain Javascript. You might want to try doing a force reload of the whole page to avoid side-effects of caching when you used the original repository before the fork for example.

**Comment by segadora** [comment]
Sure will do ASAP

**Comment by segadora** [comment]
Unable to reproduce, must be browser cache
